#
# FSharpCoreWebApi Dockerfile for building and publishing artifacts
#
# https://github.com/lrakai/FSharpCoreWebApi
#

FROM microsoft/aspnetcore-build:1.0.3-projectjson

MAINTAINER lrakai

WORKDIR /FSharpWebApi

COPY src/FSharpWebApi .

RUN dotnet restore

RUN dotnet publish --output /out/. --configuration Release
